FACEBOOK_APP_ID: "1428374111425437"
FACEBOOK_APP_SECRET: "0acad2a675114521cb751f24bacce346"
GOOGLE_CLIENT_ID: "924642446383-v3ocpiqibrad0ochst9h2gv2og3f5ed0.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "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"
LINKEDIN_CLIENT_ID: "78lxdpuk6jnadc"
LINKEDIN_CLIENT_SECRET: "W8NZYt9jB7zU7NNU"
